# Generated by Django 5.0.3 on 2024-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
