# Generated by Django 5.0.3 on 2024-04-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0004_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
